 <div class="body flex-grow-1 px-3">
        <div class="container-lg">
          <div class="row"> 
         
              
           <div class="col-sm-6 col-lg-3">
            <a href="index.php?page=documenti_gestione&idc=42" style="text-decoration: none;">
              <div class="card mb-4 text-white bg-info"  style="height:100px;">
                <div class="card-body pb-0 d-flex justify-content-between align-items-start">
                  <div>
                    <div class="fs-4 fw-semibold"><?php # $numero_totale_macchine['numero_macchine']; ?> <span class="fs-6 fw-normal">
                        <svg class="icon">
                          <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-arrow-top"></use>
                        </svg>Invia file</span></div>
                    <div>CENTRO TRASFUSIONALE POTENZA</div>
                    <?php #echo $numero_documenti['n_documenti']; ?>
                  </div>
                
                </div>
                <!-- <div class="c-chart-wrapper mt-3 mx-3" style="height:70px;">
                  <canvas class="chart" id="card-chart2" height="70"></canvas>
                </div> -->
              </div>
            </a>
            </div>

            <div class="col-sm-6 col-lg-3">
              <a href="index.php?page=documenti_gestione&idc=41" style="text-decoration: none;">
                <div class="card mb-4 text-white bg-warning"  style="height:100px;">
                  <div class="card-body pb-0 d-flex justify-content-between align-items-start">
                    <div>
                      <div class="fs-4 fw-semibold">
                        <span class="fs-6 fw-normal">
                          <svg class="icon">
                            <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-arrow-top"></use>
                          </svg>Invia file</span></div>
                      <div>CENTRO TRASFUSIONALE MELFI</div>
                      <?php #echo $numero_documenti['n_documenti']; ?>
                    </div>
                  
                  </div>
                  <!-- <div class="c-chart-wrapper mt-3 mx-3" style="height:70px;">
                    <canvas class="chart" id="card-chart2" height="70"></canvas>
                  </div> -->
                </div>
              </a>
            </div>

            <div class="col-sm-6 col-lg-3">
              <a href="index.php?page=documenti_gestione&idc=43" style="text-decoration: none;">
                <div class="card mb-4 text-white bg-danger"  style="height:100px;">
                  <div class="card-body pb-0 d-flex justify-content-between align-items-start">
                    <div>
                      <div class="fs-4 fw-semibold">
                        <span class="fs-6 fw-normal">
                          <svg class="icon">
                            <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-arrow-top"></use>
                          </svg>Invia file</span></div>
                      <div>CENTRO TRASFUSIONALE MATERA</div>
                      <?php #echo $numero_documenti['n_documenti']; ?>
                    </div>
                  
                  </div>
                  <!-- <div class="c-chart-wrapper mt-3 mx-3" style="height:70px;">
                    <canvas class="chart" id="card-chart2" height="70"></canvas>
                  </div> -->
                </div>
              </a>
            </div>
        
              
          </div><!-- ROW -->
          
          <div class="card mb-4">

             <div class="card-body">  
               <div class="table-responsive">
               <table class="table border mb-0">
                        
                        <thead class="table-light fw-semibold">
                            <tr class="align-middle">
                              <td class="text-center" colspan="6">
                                  ULTIMI 10 DOCUMENTI CARICATI IN PIATTAFORMA
                              </td><!-- comment -->
                          </tr>
                          <tr class="align-middle">

                            <th class="text-center">
                              <svg class="icon">
                                <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-people"></use>
                              </svg>
                            </th>
                           
                            <th class="text-center">Data/ora caricamento</th>
                            <th>Oggetto</th>
                          
                            <th class="text-center">Nome file</th>
                           
                          </tr>
                        </thead>

                          <tbody>
                          <?php
                                    if ($ultimi_10_documenti ) {
                                                
                                                foreach( $ultimi_10_documenti as $row_documenti) {
                                                            $data_ora_caricamento = $row_documenti["data_ora_caricamento"];  
                                                            $nome_file =  $row_documenti["nome_file"];
                                                            if (array_key_exists("nome_file_2", $row_documenti)) {
                                                              $nome_file_2 =  $row_documenti["nome_file_2"];
                                                            }
                                                            if (array_key_exists("nome_file_3", $row_documenti)) {
                                                              $nome_file_3 =  $row_documenti["nome_file_3"];
                                                            }
                                                            if (array_key_exists("nome_file_4", $row_documenti)) {
                                                              $nome_file_4 =  $row_documenti["nome_file_4"];
                                                            }
                                                           
                                                            
                                                            $oggetto =  $row_documenti["oggetto"];
                                                            $denominazione =  $row_documenti["denominazione"];
                                                         
                                   
                              ?>
                              <tr class="align-middle">
                                
                                <td class="text-center">
                                  <div><?= $denominazione; ?></div>
                                </td>

                                <td class="text-center">
                                  <div class="small text-medium-emphasis"> <?= $data_ora_caricamento; ?></div>
                                </td>
                                    
                                <td class="text-center">    
                                  <div class="clearfix">
                                    <div class="float-start">
                                      <div class="fw-semibold"><?= $oggetto; ?></div>
                                    </div>
                                  </div>
                                </td>

                                <td class="text-center">

                                  <div class="clearfix">
                                    <div class="text-center"><small class="text-medium-emphasis">
                                      <a href="../app/xcrud/documenti/<?= $nome_file; ?>" target="_blank"><?= $nome_file; ?></a>
                                    </small></div>
                                  </div>

                                  <?php if (isset($nome_file_2)) { ?>
                                  <div class="clearfix">
                                    <div class="class="text-center""><small class="text-medium-emphasis">
                                      <a href="../app/xcrud/documenti/<?= $nome_file_2; ?>" target="_blank"><?= $nome_file_2; ?></a>
                                    </small></div>
                                  </div>
                                 <?php } ?> 

                                 <?php if (isset($nome_file_3)) { ?> 
                                  <div class="clearfix">
                                    <div class="class="text-center""><small class="text-medium-emphasis">
                                      <a href="../app/xcrud/documenti/<?= $nome_file_3; ?>" target="_blank"><?= $nome_file_3; ?></a>
                                    </small></div>
                                  </div>
                                  <?php } ?> 

                                  <?php if (isset($nome_file_4)) { ?> 
                                  <div class="clearfix">
                                    <div class="class="text-center""><small class="text-medium-emphasis">
                                      <a href="../app/xcrud/documenti/<?= $nome_file_4; ?>" target="_blank"><?= $nome_file_4; ?></a>
                                    </small></div>
                                  </div>
                                </td>
                                <?php } ?>
                                </td>
                           
                              
                              </tr>
                            <?php } // END ULTIMI 10 DOCUMENTI CARICATI IN PIATTAFORMA
                                      }
                            ?>
  
  
                         
                        </tbody>
                      </table>


                    <table class="table border mb-0">
                        
                      <thead class="table-light fw-semibold">
                          <tr class="align-middle">
                            <td class="text-center" colspan="6">
                                ULTIMI 6 INGRESSI IN PIATTAFORMA
                            </td><!-- comment -->
                        </tr>
                        <tr class="align-middle">
                          <th class="text-center">
                            <svg class="icon">
                              <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-people"></use>
                            </svg>
                          </th>
                          <th>UTENTE</th>
                          <th class="text-center">NAZIONE</th>
                          <th>N. Login</th>
                        
                          <th class="text-center">ATTIVITA'</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                           <?php 
                           
                                                $img_count = 0;
                                                if ($elenco_login_utente) {
                                                foreach( $elenco_login_utente as $row_utente) {
                                                            $utente = $row_utente["utente"];  
                                                            $data_scadenza =  $row_utente["data_scadenza"];
                                                            $numero_login =  $row_utente["numero_login"];
                                                            $primo_login =  $row_utente["primo_login"];
                                                            $ultimo_login =  $row_utente["ultimo_login"];
                                                            $giorni_da_utlimo_login =  $row_utente["giorni_da_utlimo_login"];
                                                            $img_count++;
                                                }
                                                            
                                   
                            ?>
                        <tr class="align-middle">
                          <td class="text-center">
                            <div class="avatar avatar-md"><img class="avatar-img" src="img/avatars/<?= $img_count; ?>.jpg" alt="user@email.com"><span class="avatar-status bg-success"></span></div>
                          </td>
                          <td>
                            <div><?= $utente; ?></div>
                            <div class="small text-medium-emphasis"><span>Data scadenza accesso:</span> <?= $data_scadenza; ?></div>
                          </td>
                          <td class="text-center">
                            <svg class="icon icon-xl">
                              <use xlink:href="vendors/@coreui/icons/svg/flag.svg#cif-it"></use> 
                          </td>
                              
                          <td class="text-center">    
                            <div class="clearfix">
                              <div class="float-start">
                                <div class="fw-semibold"><?= $numero_login; ?></div>
                              </div>
                              <div class="float-end"><small class="text-medium-emphasis">Dal: <?= $primo_login; ?> - Al:  <?= $ultimo_login; ?></small></div>
                            </div>
                            <div class="progress progress-thin">
                              <div class="progress-bar bg-success" role="progressbar" style="width: <?= $numero_login; ?>%" aria-valuenow="<?= $numero_login; ?>" aria-valuemin="0" aria-valuemax="1000"></div>
                            </div>
                          </td>
                        
                          <td class="text-center">
                            <div class="small text-medium-emphasis">Ultimo login</div>
                            <div class="fw-semibold"><?= $giorni_da_utlimo_login; ?> giorni fà</div>
                          </td>
                         
                        </tr>
                    <?php } ?>
                    
                      </tbody>
                    </table>

                  </div>
          </div><!-- End card body user -->
          </div>
          
          
          
          
        </div><!--Container -->
        </div>
  <script  src="https://code.jquery.com/jquery-3.6.1.min.js"  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

