<div id="messaggio" class="alert alert-danger">
                                        <i class="fa fa-info"></i>
                                        <b>GESTIONE DOCUMENTI - CARICATI</b>
                                        
    </div>
   
<div class="container-fluid">
    <div class="card mb-4">
        <?php
               
                
                if ($centro >  0) {
                        echo $xcrud->render('create');
                    } else{
                        echo $xcrud->render(); 
                    }
     ?>
    </div>
  </div> 
   