<div id="messaggio" class="alert alert-info">
                                        <i class="fa fa-info"></i>
                                        <b>GESTIONE DOCUMENTI - RICEVUTI</b>
                                        
    </div>
   
<div class="container-fluid">
    <div class="card mb-4">
        <?php
               
                echo $xcrud->render(); 
     ?>
    </div>
  </div> 
   