<?php


if ( $_SESSION['utente_id_ruolo'] && $_SESSION['utente_id_ruolo'] == 1) {
    // SUPER ADMIN
    require_once 'leftsidebarsuperadmin.php';
} else if ( $_SESSION['utente_id_ruolo'] && $_SESSION['utente_id_ruolo'] == 2 || $_SESSION['utente_id_ruolo'] == 6) {
    // CTS-ADMIN
    require_once 'leftsidebarctsadmin.php';
} else if ( $_SESSION['utente_id_ruolo'] && $_SESSION['utente_id_ruolo'] == 3) {
    // CTS-SEDE
    require_once 'leftsidebarctssede.php';
}  