<!DOCTYPE html>

<html lang="en">
  <head>
    <base href="./">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="AVIS - RETE ASSOCIATIVA">
    <meta name="author" content="GIANPIERO FASULO - www.gfasulo.it">
    <meta name="keyword" content="">
    
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />

    <title>AVIS - GESTIONE RACCOLTE</title>
   
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="assets/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendors styles-->
    <link rel="stylesheet" href="vendors/simplebar/css/simplebar.css">
    <link rel="stylesheet" href="css/vendors/simplebar.css">
    <!-- Main styles for this application-->
    <link href="css/style.css" rel="stylesheet">
    <!-- We use those styles to show code examples, you should remove them in your application.-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/themes/prism.css">
    <link href="css/examples.css" rel="stylesheet">
  
  </head>
  <body>
    <div class="bg-light min-vh-100 d-flex flex-row align-items-center">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8">
                <form name="login" id="login" method="post" action="?page=controllo_login" >
                   
                    <div class="card-group d-block d-md-flex row">
              
                    <div class="card col-md-7 p-4 mb-0">
                      <div class="card-body">
                      <div class="mb-3">
                          <h1 style="display: inline;">AVIS</h1>
                          <h5  style="display: inline;" class="text-medium-emphasis text-end " > Gestione RACCOLTE</h5>
                          <div class="mb-3">
                            <span style="float:right">Accesso utenti</span>
                          </div>
                        
                      </div>
                        
                        <div class="input-group mb-3">
                            <span class="input-group-text">
                            <svg class="icon">
                              <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                            </svg>
                            </span>
                          <input class="form-control" value="" type="text" name="indirizzo_email" id="indirizzo_email" placeholder="Indirizzo E-mail">
                        </div>
                        <div class="input-group mb-4"><span class="input-group-text">
                            <svg class="icon">
                              <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                            </svg></span>
                          <input class="form-control" value="" type="password" name="password" id="password" placeholder="Password">
                        </div>
                    <!--     <div class="input-group mb-4"><span class="input-group-text">
                            <svg class="icon">
                              <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                            </svg></span>
                          <input class="form-control" type="number" name="codice_otp" id="codice_otp" placeholder="codice OTP">
                        </div> -->
                        <div class="row">
                          <div class="col-6">
                            <button class="btn btn-danger px-4" type="button" id="bottone_entra" >ENTRA</button>
                          </div>
                        <!--   <div class="col-6 text-end">
                            <a href="password_reset.php" class="btn btn-link px-0">Password dimenticata?</a>
                          </div> -->
                        </div>
                        <div class="row">
                          <div class="col-12 text-center">
                               Il tuo IP: 
                               <span id="client_ip"><?= $client_ip; ?></span>
                               <input type="hidden" name="ip_client"  value="<?= getenv("REMOTE_ADDR"); ?>">
                          </div>
                        </div>
                        
                      </div>
                    </div>
              
                       <!--  <div class="card col-md-5 text-white bg-danger">
                          <div class="card-body text-center">
                            <div>
                              <h2>QR_CODE</h2>
                              <small>Inserisci prima email e password poi clicca su Ottieni QR-CODE scansionalo ed inserisci il codice OTP nel campo OTP</small>
                              <br />
                              <span>
                                  <img src="" name="img_qr_code" id="img_qr_code" title="">
                              </span>
                              <button class="btn btn-lg btn-outline-light mt-3" id="bottone_qr_code" type="button">Ottieni QR-CODE</button>
                            </div>
                              <div id="countdown"></div>
                          </div>
                        </div> -->
                      </div>
                </form>
          </div>
        </div>
      </div>
    </div>
    <!-- CoreUI and necessary plugins-->
    <script src="vendors/@coreui/coreui/js/coreui.bundle.min.js"></script>
    <script src="vendors/simplebar/js/simplebar.min.js"></script>
    <script  src="https://code.jquery.com/jquery-3.6.1.min.js"  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script>
    
//$("body").on("contextmenu",function(){
//       alert('Tasto destro disabilitato!')
//       return false;
//}); 
    
    
$('#bottone_qr_code').on("click", function () {
    let timeleft = 0;
    let downloadTimer = 0;
    document.getElementById("countdown").innerHTML = "";
    
        if ( $('#indirizzo_email').val() === '' || $('#password').val() === ''){
                       alert('Prima di richiedere il QR-CODE compila i campi email e password');
                       return false;
                    } else if ( $('#client_ip').text() === '' ) {
                        alert('IP non VALIDO!');
                       return false;
                    }
    
                    $('#img_qr_code').attr('src','');
                    let email = $('#indirizzo_email').val();
                    let password = $('#password').val();
                    let client_ip = $('#client_ip').text();
        
                    $.ajax({   
                            url: "./api/get_qr_code.php",
                            data: { indirizzo_email: email, password: password, client_ip: client_ip},
                            type: 'POST',
                            dataType: "json",
                            success: function (data) { 
                                if ( data == null ) {
                                     alert('ATTENZIONE AUTENTICAZIONE FALLITA.');
                                    return false;
                                } 
                                  let urlencoded = data.qrCodeUrl;
                                  $('#img_qr_code').attr('src',urlencoded);
                                  
                                  // TIMER 30 SECONDO AVVISO CODICE SCADUTO
                                    timeleft = 30;
                                    downloadTimer = setInterval(function(){
                                  if(timeleft <= 0){
                                    clearInterval(downloadTimer);
                                    document.getElementById("countdown").innerHTML = "QR-CODE scaduto richiederne un'altro";
                                    $('#bottone_qr_code').prop("disabled",false);
                                  } else {
                                    document.getElementById("countdown").innerHTML = timeleft + " secondi alla scadenza del codice";
                                    $('#bottone_qr_code').prop("disabled",true);
                                  }
                                  timeleft -= 1;
                                }, 1000);
                              },
                                error:function(){
                                    alert('ATTENZIONE ERRORE ACQUISIZIONE QR-CODE.');
                                    return false;
                                }
                            });
                                
}); 

$('#bottone_entra').on("click", function (event) { 
   
      let controllo = '';
      
                    if ( $('#indirizzo_email').val() === '' || $('#password').val() === '' || $('#codice_otp').val() === ''){
                        controllo = false;
                    } else {
                        controllo = true;
                    }         
                    
                    let email = $('#indirizzo_email').val();
                    let password = $('#password').val();
                    
                    if( !validateEmail(email)) { alert('INDIRIZZO EMAIL NON VALIDO'); }
              
                
                if ( controllo === true ) {
                           
                            $.ajax({   
                                url: "api/controlla_login.php",
                                data: { indirizzo_email: email, password: password},
                                type: 'POST',
                                dataType: 'json',
                                success: function (data) { 
                             
                                      if ( data) {
                                          document.getElementById("login").submit();
                                      }
                              
                            },
                              error:function(){
                                  alert ('Dati di login errati');
                                  return false;
                              }
                          }); // END CARICAMENTO DATI ANAGRAFICA UTENTE
                      } else {
                          alert ('Tuti i campi sono obbligatori');
                                  return false;
                      }
                      
                  
         
      }); // END CLICK
      
function validateEmail($email) {
  var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
  return emailReg.test( $email );
}
</script>

  </body>
</html>
