
    <div class="bg-light  d-flex flex-row align-items-center">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6">
            <div class="clearfix">
              <h1 class=" text-center">MODIFICA DATI</h1>
              <br />
              
             
            </div>
          <h4 class="pt-3 text-center"><?= $messaggio; ?></h4>
          <p class="text-center"> <a href="?page=logout" class="text-danger">RIEFFETTUA IL LOGIN PER SICUREZZA</a></p>
          </div>
           
        </div>
      </div>
    </div>
   